/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cute_bunny.glb 
Author: Ndevisuals (https://sketchfab.com/Wade23)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-bunny-037f632eb1cc45889219629187df68db
Title: Cute Bunny
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cute_bunny.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Kain} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/cute_bunny.glb')
